
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${servidorBD}:${puertoBD}/viajes?serverTimezone=UTC
    username: root
    password: root   
  jpa:
    hibernate:
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
eureka:
  client:
    serviceUrl:
      defaultZone: http://${servidorEureka}:${puertoEureka}/eureka
  instance:
    hostname: ${host}  //Indica que se registrara en el servicio de descubirmiento con su direccionn ip
server:
  port: 8000
